/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ouyadi' at '8/25/16 10:53 PM' with Gradle 2.14
 *
 * @author ouyadi, @date 8/25/16 10:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
